### ISSUE TITLE
The loader persist when the app runs.

### ISSUE THREAD

**Issue by valens200** [phetsims/diffusion#10]

**Comment by brettfiedler** [comment]
Hi @valens200,

We're excited to see you here and your interest in contributing! If I may ask, is there something in particular you would like to contribute? Is there something in the Diffusion simulation you'll looking to add to or solve?

I would like to invite you to head over to the [SceneryStack community](https://scenerystack.github.io/community/), as that has the most comprehensive and up to date information on the development libraries used to make PhET simulations, as well as contribution information. I'd recommend checking out the [Contributing doc](https://scenerystack.github.io/community/CONTRIBUTING/).

We'll need a bit more information to help out with your problem. Any other details on what instructions you followed and your current setup would be helpful! I'd encourage you to check out the [Simulation Development Overview](https://scenerystack.github.io/community/info-sync/simulation-development-overview/) and follow each step to help with your build. You may be missing an html-server or transpiler step.

Thanks!

**Comment by pixelzoom** [comment]
No response from the submitter, so I'm closing this issue.  @brettfiedler FYI.

**Comment by pixelzoom** [comment]
I'm preparing this sim for RC testing.  There has been no response from the submitter, so I'm closing this issue. @brettfiedler FYI.
