### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/diffusion#2]
This sim current shares it credits info with Gas Properties, because I suspect that credits will be indentical to Gas Properties.  @arouinfar if you agree, please close this issue and we'll continue to track credits in https://github.com/phetsims/gas-properties/issues/28.

**Comment by arouinfar** [comment]
That sounds reasonable to me @pixelzoom. 

I'd close this issue, but I don't appear to have the appropriate permissions.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  Permission for collaborators were wrong on the repo, they are fixed now.

Closing.
