### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/diffusion#4]
For https://github.com/phetsims/QA/issues/387 and #1 
This sim is being published for the first time, and so it needs screenshots and alt screenshots. @arouinfar let me know what you would like them to look like and when you think the sim is settle enough to take them, then assign back to me.

**Comment by arouinfar** [comment]
@KatieWoe please take screenshots during rc.2.

### Main screenshot
Particles starting to mix, and clearly biased Particle Flow Rate arrows.
![Diffusion-1](https://user-images.githubusercontent.com/8419308/62251824-3700ee00-b3ae-11e9-898e-28c6f52a853c.png)

### Alt 1
Center of mass markers merging, but not at equilibrium. Exact TimerNode reading is unimportant.
![Diffusion-2](https://user-images.githubusercontent.com/8419308/62251825-3700ee00-b3ae-11e9-8cd7-84fdc71a5f30.png)

### Alt 2
Take screenshot soon after removing divider.
![Diffusion-3](https://user-images.githubusercontent.com/8419308/62251826-3700ee00-b3ae-11e9-9941-137eda7ed5e3.png)

**Comment by KatieWoe** [comment]
Here are the screenshots for this sim:
![diffusion-screenshot](https://user-images.githubusercontent.com/41024075/62328830-5d3b9200-b471-11e9-8cf3-158352d78b4e.png)
![diffusion-screenshot-alt1](https://user-images.githubusercontent.com/41024075/62328831-5d3b9200-b471-11e9-8e98-43663dfe3936.png)
![diffusion-screenshot-alt2](https://user-images.githubusercontent.com/41024075/62328832-5dd42880-b471-11e9-89a2-49b16afe15ec.png)

**Comment by KatieWoe** [comment]
@arouinfar to approve

**Comment by arouinfar** [comment]
Looks good, thanks @KatieWoe!

**Comment by KatieWoe** [comment]
Done.  Closing
